spring:
  application:
    name: InvexTrack
  datasource:
    url: jdbc:mysql://localhost:3306/invextrack_db
    username: root #Aqui va tu usuario
    password: #Aqui va tu contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always # Ejecuta schema.sql y data.sql al arrancar

  jpa:
    hibernate:
      ddl-auto: none # Desactiva la creación automática de Hibernate para usar los scripts .sql
    show-sql: true

# Configuración de Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
